name: Shivansh Master Playlist

on:
  schedule:
    - cron: "*/15 * * * *"   # Runs every 15 minutes
  workflow_dispatch:

concurrency:
  group: shivansh-m3u
  cancel-in-progress: false   # ✅ Queue new runs instead of canceling

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        run: |
          sudo apt update
          sudo apt install -y curl jq

      - name: Build or update master playlist
        run: |
          # 🔁 Replace this with your actual playlist source/update logic
          curl -s "https://example.com/master.m3u" -o master.m3u

      - name: Replace credit line permanently
        run: |
          sed -i 's|#EXTINF:-1 tvg-id="12321" group-title="Movies" tvg-logo="https://t.me/ygxworld",by @ygxworld|#EXTINF:-1 tvg-id="1" group-title="Credits" tvg-logo="https://i.postimg.cc/MZftPYPB/IMG-20250710-192112-387.jpg",by @Shivansh|g' master.m3u
          echo "✅ Credits updated successfully for $P Exclusive (Shivansh)"

      - name: Commit and push changes
        run: |
          git config --global user.name "ShivanshBot"
          git config --global user.email "shivanshbot@example.com"
          git add master.m3u
          git commit -m "Updated $P Exclusive (Shivansh) playlist and credits" || echo "No changes to commit"
          git push
