import yaml, datetime, glob, os

# Load YAML
config_path = "m3u_merge_config.yml"
with open(config_path, 'r', encoding='utf-8') as f:
    config = yaml.safe_load(f)

# Load creds.txt sources
sources = []
with open(config["settings"]["source_list"], 'r', encoding='utf-8') as f:
    for line in f:
        src = line.strip()
        if src and os.path.exists(src):
            sources.append(src)

if not sources:
    print("❌ No valid sources found in creds.txt.")
    exit(1)

# Read and merge all M3Us
seen = set()
channels = []
for src in sources:
    with open(src, 'r', encoding='utf-8', errors='ignore') as f:
        content = f.readlines()
    for i in range(len(content)):
        if content[i].startswith('#EXTINF'):
            url = content[i+1].strip() if i + 1 < len(content) else ''
            key = (content[i].strip(), url)
            if key not in seen:
                seen.add(key)
                channels.append((content[i], url))

# Stats
now = datetime.datetime.now(datetime.timezone(datetime.timedelta(hours=5, minutes=30)))
timestamp = now.strftime("%Y-%m-%d %H:%M IST")
next_update = (now + datetime.timedelta(minutes=config["settings"]["update_interval"])).strftime("%Y-%m-%d %H:%M IST")

total = len(channels)
updated = total  # For simplicity, treat all as updated

# Header template (Morning example, can add condition for time-based later)
header = f'''#EXTM3U billed-msg="RJM Tv - RJMBTS Network"
# =========================================================
# ☀️ Auto Generated by RJM AutoBot
# 🕒 Last updated on : {timestamp}
# 🔁 Next update     : {next_update}
# 📊 Channels : Total - {total} | Updated - {updated}
# =========================================================
'''

footer = '''
# =========================================================
# ⚡ Exclusively for RJM Tv - Powered by RJMBTS ⚡
# =========================================================
'''

# Write Master.m3u
with open(config["settings"]["output_file"], 'w', encoding='utf-8') as out:
    out.write(header)
    for extinf, url in channels:
        out.write(f"{extinf}\n{url}\n")
    out.write(footer)

print(f"✅ Generated Master.m3u with {total} channels.")
